# Generated by Django 4.2.18 on 2025-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_pdf', models.FileField(upload_to='Files/pdfs/')),
                ('uplaod_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
