# Generated by Django 4.2.18 on 2025-03-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='uplaod_at',
            new_name='uploaded_at',
        ),
    ]
