# Generated by Django 4.2.18 on 2025-03-13 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_update_at_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='file_pdf',
            field=models.FileField(upload_to='Files/'),
        ),
    ]
